version: '3'
services:
  ms:
    image: metasploitframework/metasploit-framework:latest
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    links:
      - db
    ports:
      - 443:443
    volumes:
      - $HOME/msf:/home/msf

  db:
    image: postgres:12-alpine
    volumes:
      - $HOME/msf/pbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: msf
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
